# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'teleprompter-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'NVActivityIndicatorView'
  # Pods for teleprompter-ios
  pod 'Alamofire', '~> 4.7'
  
  target 'teleprompter-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'teleprompter-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
